title: My Site
description: My very nice site

url: 'n-at-han-k.github.io'
baseurl: '/jekyll-tailwind-stimulus'

#importmap:
  #devurl: 'http://127.0.0.1:4000/jekyll-tailwind-stimulus'

plugins:
  - jekyll-postcss
  - jekyll-importmap

postcss:
  cache: false

exclude: 
  - .gitignore
  - .github
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - node_modules
  - package-lock.json
  - Dockerfile
  - importmap.rb
  - yarn-error.log

include:
  - _pages

#########################################
# CUSTOM BELOW
